### PR TITLE
Do not require react-addons-perf

### PR DESCRIPTION
**Pull request by rt2zz**
This removes react-addons-perf which seems to be unavailable in 15.1, although someone who actually uses this should probably weigh in as it may have simply moved locations.

The specific observed error prompting this change was: `Error: Cannot find module 'react/lib/ReactDefaultPerf'`

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
I'm not sure this is a valid solution. I've never had this problem before. We are requiring the library properly to the latest version. Could you update to the latest version and try again. Make sure you install the dependancies properly

**Comment by evollu** [comment]
I have the same issue after react 15.1 upgrade

**Comment by RealOrangeOne** [comment]
@evollu Are you having this issue using the latest version of `react-native-mock` (`0.2.3`), or an older version. You must be using the latest version. Only `0.2.3` will work with RN 0.27

**Comment by evollu** [comment]
I tried 0.2.2 yesterday. I will try 2.3 today

**Comment by evollu** [comment]
0.2.3 is working for me

**Comment by RealOrangeOne** [comment]
@rt2zz Can you retry with version `0.2.3`, and close if problem solved.

**Comment by rt2zz** [comment]
:+1:
