### ISSUE TITLE
Cannot find module 'ReactPerf' from 'react-native.js'

### ISSUE THREAD

**Issue by chinesedfan** [lelandrichardson/react-native-mock#167]
Even with the help of https://github.com/azarashd/react-native-mock, it can't work in RN 0.59.

Based on @azarashd's work, I did two more things in [my fork](https://github.com/chinesedfan/react-native-mock) to solve.

- Unless you really need it, comment this line https://github.com/RealOrangeOne/react-native-mock/blob/4c33a4de618b7a3c4cb8922884ae5dd7cc4218bf/src/react-native.js#L111.
- Revert `react-timer-mixin` as a dependency, as `react-native` doesn't include it any more.
